In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Dataset 1

In [21]:
data1 = pd.read_csv(r'C:\Users\hephz\OneDrive\Documents\GitHub\div_lessons\Hackathon_Team6\covid19vacbydemographics.csv')
data1
data1.head()

,demographic_category,demographic_value,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,booster_recip_count,cumulative_booster_recip_count
0,Age Group,18-49,08/03/2022,8219,33212597,5311,19574942,2649,12321983,242,1301298,1475,1766522,1455,13112504,1624,14879026,5061,6120140
1,Age Group,50-64,08/03/2022,2937,16332473,1651,8659419,1190,6919606,81,738914,365,665935,344,6199910,397,6865844,1995,3745822
2,Age Group,65+,08/03/2022,1951,14770183,973,6934877,907,7574521,28,243663,194,603187,204,5396702,202,5999889,1117,3796654
3,Age Group,Dec-17,08/03/2022,1919,5213509,1905,5192333,1,10648,0,1299,346,259772,509,2075192,348,2334961,1050,570676
4,Age Group,05-Nov,08/03/2022,3298,2484587,67,38657,0,1696,0,249,1353,225117,1933,1120692,1353,1345808,7,1258

In [ ]:
data1.info()
data1.value_counts()

# Dataset 2

In [22]:
data2 = pd.read_csv(r'C:\Users\hephz\OneDrive\Documents\GitHub\div_lessons\Hackathon_Team6\covid19vaccinesbycounty.csv')
data2
data2.head()

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count
0,Alameda,05/01/2020,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
1,Alameda,03/03/2020,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
2,Alameda,27/07/2020,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
3,Alameda,29/07/2020,0,1,0,0,0,1,0,0,0,0,0,0,0,1,NaN,0,0
4,Alameda,30/07/2020,0,1,0,0,0,1,0,0,0,0,0,0,0,1,NaN,0,0

In [ ]:
data2.info()